### ISSUE TITLE
outputs.all does not include deleted files

### ISSUE THREAD

**Issue by LongLiveCHIEF** [lots0logs/gh-action-get-changed-files#23]
I am seeing consistently that runs where I delete a file, that the deleted file is not included in the `outputs.all`.

Here's an example commit: https://github.com/LongLiveCHIEF/atsamd/commit/ad1e8762f680132ea2723636f5c5faba32e5878f
and the associated run: https://github.com/LongLiveCHIEF/atsamd/runs/3792750091?check_suite_focus=true#step:5:33

In the line referenced, the input to the `generateBuildMatrix` is from `outputs.all`.  Notice how in the commit above, i changed the action file, and deleted one of the src files, but the array in the function only contains the modified file.

**Comment by lots0logs** [comment]
That is intentional and it is documented in the README.
