### ISSUE TITLE
Upgrade to NodeJS 16

### ISSUE THREAD

**Issue by OrBin** [lots0logs/gh-action-get-changed-files#26]
This action [uses NodeJS 12](https://github.com/lots0logs/gh-action-get-changed-files/blob/master/action.yml#L5), which is deprecated in GitHub Action [since September 22nd](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).

Can you please upgrade this action to NodeJS 16 to keep compatibility?

**Comment by MCKevmeister** [comment]
@lots0logs Would like to know if this could happen before this action would fail at the end of the month?
