### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by Poolitzer** [lots0logs/gh-action-get-changed-files#8]
Hey guys,

seems to be the same error as in #2, just a different file.

 ```
/home/runner/work/_actions/lots0logs/gh-action-get-changed-files/2.0.6/dist/main.js:3567
const commits = context.payload.commits.filter(c => c.distinct);
                                        ^

TypeError: Cannot read property 'filter' of undefined
```

Full runthrough with error (just trying your action out here ;P): https://github.com/python-telegram-bot/python-telegram-bot/pull/1786/checks?check_run_id=459027793#step:6:1

Your action is implemented [here](https://github.com/python-telegram-bot/python-telegram-bot/blob/type_hinting_master/.github/workflows/mypy.yml#L27), should be correct.

**Comment by grantmcconnaughey** [comment]
I got this same error as well when attempting to use this Action with version 2.0.6.

**Comment by ndibari-etsy** [comment]
Hi is there any update on this? Also got the same error on version 2.0.6. Is there a version that does work in the meantime that we can use?

**Comment by lots0logs** [comment]
Sorry for not noticing this issue before now. I can confirm that v2.0.5 works without issue so long as its used on repos owned by an organization. Not sure when I will have time to look into this new error but I will do it asap.

**Comment by sgibson91** [comment]
I hate to be the bearer of bad new but I am also seeing this error with v2.0.5 😬

> ... so long as its used on repos owned by an organization.

Can you explain what you mean by this please? This is the repo I'm working on, definitely owned by an org https://github.com/alan-turing-institute/the-turing-way

**Comment by Poolitzer** [comment]
Maybe he meant PRs from inside the organization

**Comment by sgibson91** [comment]
Hi @Poolitzer! I've branched, not forked, and I'm a member of that org ☺️

**Comment by Poolitzer** [comment]
Destroying my theories in an instant, pfff :(

**Comment by lots0logs** [comment]
What I meant by that was that the repo is owned by an org account and not a personal user account. We are using v2.0.5 without issue at the company I work for.

**Comment by Poolitzer** [comment]
My PR situation is also owned by a company/collective

**Comment by lots0logs** [comment]
I'll have to dig deeper into this. Not sure off hand what is causing the failure.

**Comment by serucee** [comment]
Hi,

this happens when the action is used in a pull request (atleast for me) and is resolved when using it on push. I assume the payload used in https://github.com/lots0logs/gh-action-get-changed-files/blob/master/main.js#L6 isn't available in the same way for pull requests.

**Comment by lots0logs** [comment]
Thanks. That is helpful!

**Comment by ThiefMaster** [comment]
Happens for me as well and makes this action useless for me - which is a shame, because it's the only action to get a list of changed files that actually looks decent.

**Comment by lots0logs** [comment]
I'm happy to review a pull request from anyone who has the time to add support for events other than `push`. I just don't have time right now. Especially since we only use this action on the `push` event at my job so it works fine.

**Comment by adamjstewart** [comment]
I encountered the same problem, this action does not work for pull requests. For what it's worth, https://github.com/marketplace/actions/file-changes-action has almost identical functionality and works fine for me on pull requests.
